version: '3.3'

services:
  influx:
    image: influxdb:1.8
    volumes:
      - type: bind
        source: /path/to/influx/data
        target: /var/lib/influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: true
      INFLUXDB_META_LOGGING_ENABLED: false
      INFLUXDB_DATA_INDEX_VERSION: tsi1
      INFLUXDB_COORDINATOR_QUERY_TIMEOUT: 10s
      INFLUXDB_COORDINATOR_LOG_QUERIES_AFTER: 5s
      INFLUXDB_HTTP_FLUX_ENABLED: true
      INFLUXDB_HTTP_LOG_ENABLED: false
      INFLUXDB_DATA_QUERY_LOG_ENABLED: false
      INFLUXDB_DATA_MAX_CONCURRENT_COMPACTIONS: 1
      INFLUXDB_RETENTION_CHECK_INTERVAL: 360m0s
      INFLUXDB_LOGGING_LEVEL: info
      INFLUXDB_BIND_ADDRESS: 0.0.0.0:8088
    ports:
      - "0.0.0.0:8086:8086"
      - "0.0.0.0:8088:8088"
    restart: always

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - type: bind
        source: /path/to/grafana/data
        target: /var/lib/grafana
    environment:
      GF_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION: 365d
      GF_LOGIN_MAXIMUM_LIFETIME_DURATION: 365d
    ports:
      - "3000:3000"
    restart: always