{
 "title": "Weather",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Location", "query": { "query": "label_values(location)" } }
  ]
 },
 "panels": [
  {
   "title": "Room Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_f{location=~\"$Location\"}[30m])",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "% Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_charge{location!=\"living_room\",location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Temperature °F",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "weather_temperature_f{location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Pressure kPa",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "expr": "weather_pressure{location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "% Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "weather_humidity{location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "% Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "battery_charge{location!=\"living_room\",location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "battery_voltage{location!=\"living_room\",location=~\"$Location\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  { "title": "In Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Rate of Change",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "delta(weather_temperature_f{location=~\"$Location\"}[30m])",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}