{
 "title": "Weather",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Locations",
    "query": "SHOW TAG VALUES WITH KEY=\"location\""
   },
   {
    "name": "Interval",
    "query": "1s,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Room Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature °F",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure kP",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 8, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT last(\"pressure\") FROM \"weather\" WHERE (\"location\" =~ /^$Locations$/) AND $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Living Room Comfort",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  }
 ]
}