{
 "title": "Weather",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Locations",
    "label": "Locations",
    "query": "SHOW TAG VALUES WITH KEY=\"location\""
   },
   {
    "name": "Interval",
    "query": "1s,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Room Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" },
      { "condition": "AND", "key": "location", "operator": "!=", "value": "living_room" }
     ]
    }
   ]
  },
  {
   "title": "Temperature °F",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure kP",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT last(\"pressure\") FROM \"weather\" WHERE (\"location\" =~ /^$Locations$/) AND $timeFilter GROUP BY time($__interval), \"location\" fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "% Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" },
      { "condition": "AND", "key": "location", "operator": "!=", "value": "living_room" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" },
      { "condition": "AND", "key": "location", "operator": "!=", "value": "living_room" }
     ]
    }
   ]
  },
  {
   "title": "Room Comfort",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Check-Ins Per Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Dew Point",
   "type": "stat",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Dew Point Celcius",
     "query": "SELECT LAST(temperature_c) - ( (100 - LAST(humidity)) / 5 ) AS dew_point_c FROM weather WHERE location='outside';"
    },
    {
     "alias": "Dew Point Fahrenheit",
     "query": "SELECT ((LAST(temperature_c) - ( (100 - LAST(humidity)) / 5 )) * 9/5) + 32 AS dew_point_f FROM weather WHERE location='outside';"
    }
   ]
  },
  {
   "title": "Change Over Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  }
 ]
}